name: Build and Publish Javadocs

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout the Repository to Runner
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository  # Important: path must match inside container
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build Maven Javadocs
        run: mvn javadoc:javadoc javadoc:test-javadoc

      - name: Prepare Javadocs for Github Pages
        shell: bash
        run: |
          cp -r target/reports github-pages/javadocs

      - uses: ./.github/publish-github-pages