name: Test Execution and Publish Report

on:
  workflow_dispatch:
    inputs:
      TOKEN_EXPIRY_SECONDS:
        required: false
        type: number
        description: Token Expiry Override (Seconds)

      parallel:
        description: Run Test in Parallel
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pages: write

env:
  AMADEUS_TEST_SECRET: ${{ secrets.AMADEUS_TEST_SECRET }}

jobs:
  test-execution:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout the Repository to Runner
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository # Important: path must match inside container
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Execute Test
        run: |
          EXTRA_PARAMS=""
      
          if [[ "${{ inputs.parallel }}" == "true" ]]; then
            EXTRA_PARAMS+=" -Dparallel=true";
          fi

          if [[ -n "${{ inputs.TOKEN_EXPIRY_SECONDS }}" ]]; then
            EXTRA_PARAMS+=" -DTOKEN_EXPIRY_SECONDS=${{ inputs.TOKEN_EXPIRY_SECONDS }}";
          fi

          echo "Running with: mvn clean test ${EXTRA_PARAMS}"
          mvn clean test ${EXTRA_PARAMS}

      - name: Generate Allure Report
        if: success() || failure()
        uses: NayeemJohnY/actions/allure-report-with-history@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Build Maven Javadocs
        if: success() || failure()
        run: mvn javadoc:javadoc javadoc:test-javadoc

      - name: Prepare GitHub Pages Content
        if: success() || failure()
        uses: NayeemJohnY/actions/prepare-github-pages@main
        with:
          reports-dir: test-results/allure-report
          javadoc-dir: target/reports

      - name: Deploy GitHub Pages
        if: success() || failure()
        uses: NayeemJohnY/actions/deploy-github-pages-site@main
